name: Build

on:
  workflow_call:

jobs:
  build_wheels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      # Keep release title in sync with the latest matching tag
      - name: Retrieve version from git tags
        id: version
        run: |
          echo "TAG_NAME=$(git describe --match "v*" --tags)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Build wheels
        run: python -m pip wheel -w dist .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          retention-days: 1
          path: ./dist/*.whl
